"""
Weekly Market Report generator.

Produces a markdown report from the analytics dict.
Output: reports/weekly_market_report_YYYY-MM-DD.md
"""

import logging
from datetime import date
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def _fmt_aed(value: Optional[float]) -> str:
    if value is None:
        return "N/A"
    if value >= 1_000_000:
        return f"AED {value/1_000_000:.2f}M"
    if value >= 1_000:
        return f"AED {value/1_000:.0f}K"
    return f"AED {value:,.0f}"


def _fmt_ppsf(value: Optional[float]) -> str:
    if value is None:
        return "N/A"
    return f"AED {value:,.0f}/sqft"


def _change_str(wow: dict) -> str:
    change = wow.get("change")
    pct = wow.get("change_pct")
    if change is None:
        return ""
    sign = "+" if change >= 0 else ""
    pct_str = f" ({sign}{pct}%)" if pct is not None else ""
    return f"{sign}{change}{pct_str}"


def generate_report(analytics: dict, reports_dir: Path) -> Path:
    """
    Build the weekly markdown report and write it to reports_dir.
    Returns the path to the written file.
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_date = analytics.get("date", date.today().isoformat())
    output_path = reports_dir / f"weekly_market_report_{report_date}.md"

    total = analytics.get("total_listings", 0)
    areas = analytics.get("areas", {})
    wow = analytics.get("week_on_week", {})

    lines = [
        f"# Dubai Real Estate Intelligence Report",
        f"**Week ending: {report_date}**",
        f"",
        f"> Data collected from PropertyFinder, Bayut, and Dubizzle.",
        f"> All figures are based on listing prices — not transaction prices.",
        f"> Only real, verified data is included.",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total listings collected | {total:,} |",
        f"| Areas covered | {len(areas)} |",
        f"| Report generated | {report_date} |",
        f"",
        f"---",
        f"",
        f"## Area Breakdown",
        f"",
    ]

    for area, stats in sorted(areas.items()):
        count = stats.get("listings_count", 0)
        avg_price = stats.get("avg_price")
        min_price = stats.get("min_price")
        max_price = stats.get("max_price")
        avg_ppsf = stats.get("avg_price_per_sqft")
        bed_dist = stats.get("bedroom_distribution", {})
        sources = stats.get("sources", {})
        area_wow = wow.get(area, {})

        lines += [
            f"### {area}",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Listings | {count:,} |",
            f"| Average price | {_fmt_aed(avg_price)} |",
            f"| Min price | {_fmt_aed(min_price)} |",
            f"| Max price | {_fmt_aed(max_price)} |",
            f"| Avg price/sqft | {_fmt_ppsf(avg_ppsf)} |",
            f"| Week-on-week change | {_change_str(area_wow)} |",
            f"",
        ]

        if bed_dist:
            lines.append("**Bedroom distribution:**")
            lines.append("")
            lines.append("| Bedrooms | Listings |")
            lines.append("|----------|----------|")
            for beds, cnt in sorted(bed_dist.items()):
                lines.append(f"| {beds} | {cnt:,} |")
            lines.append("")

        if sources:
            lines.append("**Sources:**")
            lines.append("")
            for src, cnt in sorted(sources.items()):
                lines.append(f"- {src}: {cnt:,} listings")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines += [
        "## Notes",
        "",
        "- Listing prices are **not** transaction prices.",
        "- Price per sqft is derived from listing price ÷ listed size.",
        "- Records without a price or area are excluded.",
        "- Duplicate URLs are counted once.",
        "",
        "---",
        "",
        "*Generated by Dubai Real Estate Intelligence Platform V1*",
    ]

    content = "\n".join(lines)
    output_path.write_text(content, encoding="utf-8")
    logger.info("Report written → %s", output_path)
    return output_path
